# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161121_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='biography',
            field=models.TextField(blank=True, default=''),
        ),
    ]
